---
- name: Install APT packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
    - python3
    - python3-pip
    - python3-dev
    - libpq-dev


- name: Update pip and setuptools
  pip:
    name: "{{ item }}"
    state: latest
    executable: pip3
  with_items:
    - pip
    - setuptools